### ISSUE TITLE
Close quic.BidirectionalStream when data.Finished = true while sending data

### ISSUE THREAD

**Issue by vrngupta53** [pion/quic#33]
In bidirectionalstream.go, 
func (s *BidirectionalStream) Write(data StreamWriteParameters) error {
	_, err := s.s.WriteQuic(data.Data, data.Finished)
	return err
}
The stream is not closed even if data.Finished is true, this is mentioned as a TODO in the comment in func WriteQuic in internal/wrapper/stream.go which is called by the Write function. 
What should I do to close a stream?

**Comment by cryptix** [comment]
@vrngupta53 would be great if you could try PR #32. Apart from updating the underlying implementation it also fixes this closing bug and making sure data that is part of the close frame is read back as expected.
