### ISSUE TITLE
is there a code that can issue http3 or use quic like this? 

### ISSUE THREAD

**Issue by gitmko0** [pion/quic#48]
this is from fasthttp, it automatically issues all domain names https using letsencrypt
https://play.golang.org/p/yyF3_n4Ag4d

**Comment by Sean-Der** [comment]
Hey @gitmko0 

I think you want to file this against https://github.com/lucas-clemente/quic-go 

This library is for adding RtcQuicTransport to https://github.com/pion/webrtc
