### ISSUE TITLE
Client suport libs for non golang 

### ISSUE THREAD

**Issue by joeblew99** [pion/quic#6]
QUIC is really interesting and especially that it can do P2P and Client / Server and has a spec for it.  I had no idea there were specs for these networking topology use cases. Its great though !

I wonder what languages currently support this ( or are along the way to supporting this) ?
The reasoning is that sure its awesome, but we dont always have the luxury of controlling the client end ( mobiles, web, etc) that developers use. So its not always golang clients.

SO i raise this so tat we can flesh out how far along client libs are.

c#, java, python, dart are some of my targets.

**Comment by Sean-Der** [comment]
Hey @joeblew99 

Sorry I never got around to responding on it. I am going to resolve since we dropped QUIC support. libwebrtc removed RtcQuicTransport so we have removed it as well.

thanks
